### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by PencilWarrior1** [carlosvega/edx-video-extension#1]
Hey there,

I enabled Developer mode and tried load unpacked, but received a "Failed to load extention error."  Any ideas?

File	~\Downloads\edx-video-extension-master
Error	Could not load icon 'icon.png' specified in 'browser_action'.
	Could not load manifest.

Thx.

**Comment by carlosvega** [comment]
Hi, it should be fixed now. Thanks for reporting the issue!
