### ISSUE TITLE
Installed your extension on developer mode but doesn't find source video

### ISSUE THREAD

**Issue by tfrazao-tech** [carlosvega/edx-video-extension#2]
Browser: Chrome Version 86.0.4240.111 (Official Build) (64-bit)

Step - Click on View Sources with the edx page course open;

Outcome - Nothing happens.

**Comment by Eyespiral** [comment]
+1

**Comment by carlosvega** [comment]
Hi, 

thanks for reporting your issue. I just tried with one course, and seems to work. I tested the same Chrome version. It might be another extension conflicting? Are there any errors on the JavaScript Console? (right click > Inspect > Console and check the option Preserve log in the screw icon on the right side to keep the log while you browse).

The steps to follow:
- Go to a video page of a course (see image as example). 
- Then open the extension.

<img width="1196" alt="Screenshot 2020-11-04 at 21 40 36" src="https://user-images.githubusercontent.com/1414389/98165551-61f9bc00-1ee6-11eb-99b9-cda3209ca48a.png">

Could you provide me with the link to the course or a video to reproduce the issue?

**Comment by tfrazao-tech** [comment]
> Hi,
> 
> thanks for reporting your issue. I just tried with one course, and seems to work. I tested the same Chrome version. It might be another extension conflicting? Are there any errors on the JavaScript Console? (right click > Inspect > Console and check the option Preserve log in the screw icon on the right side to keep the log while you browse).
> 
> The steps to follow:
> 
> * Go to a video page of a course (see image as example).
> * Then open the extension.
> 
> <img alt="Screenshot 2020-11-04 at 21 40 36" width="1196" src="https://user-images.githubusercontent.com/1414389/98165551-61f9bc00-1ee6-11eb-99b9-cda3209ca48a.png">
> 
> Could you provide me with the link to the course or a video to reproduce the issue?

this is the error that appears from content.js
![image](https://user-images.githubusercontent.com/46816885/98289039-82d21800-1f9f-11eb-868e-8368fe25ec16.png)

I was able to download but after clicking a few times on the extension icon and then the button...but I can't replicate.

from popup.js there was nothing in the inspect window.

thanks for your help 👍

**Comment by Eyespiral** [comment]
> +1

I think I legitimately failed to close and restart Chrome. When I did that today it started working. Facepalm. Thanks for this tool.

**Comment by carlosvega** [comment]
Thanks for the feedback!
